### ISSUE TITLE
decide on chat approach (tech, architecture, etc)

### ISSUE THREAD

**Issue by aconanlai** [n10as/n20.as#7]

**Comment by aconanlai** [comment]
- socket.io - mongodb ?
- if storing temp user sessions, mongo or redis?
- kick people with socket.disconnect(), + remove all their messages? - store list of banned IPs in mongo
- user logs in with username, no authentication required but should we have option for protected usernames? n10.as, kuzyn, etc
- where is admin panel for chat - embedded right in the chat (cons: additional overhead of auth logic and passing different components based on user admin level - pros: more user friendly) or in the CMS route (cons: admin panel must be accessed separately from chat itself but may not be a problem since kicking/banning/deleting messages should be extremely rare, pros: much quicker to develop feature that doesn't need to be UI/UX optimized)

**Comment by kuzyn** [comment]
Here's some quick thoughts as well:

1. First iteration should do without admin function
1. Is it important to preserve history?
1. I'd say we try to sitck with socket.io/mongo to avoid adding complexity (even if it means slightly less optimal solutions)
1. protected names 👍 stored in db
1. re: admin functions for chat; pretty much agree. endgoal is to have it seemless

**Comment by aconanlai** [comment]
1. agree
2. pretty important, people like being able to come on the site and see what people have been saying the past hours/day - currently we clear msgs once they're 12 hours old, can think of best way to do this
3. can you expand? implementations i've seen use one mongo collection for msgs, and a separate one for user session data:
https://github.com/OmarElGabry/chat.io

is the chat run on the same dyno as our server + client? same node process?

**Comment by kuzyn** [comment]
Yes all on the same process

As for 3: what I mean is that (without looking into the detail of actual implementations) I would try to minimize adding new components to the app as much as we can, while we hone what's already in place. If they are using Redis to store usersession, could we do it with mongo? Could we cache it elsewhere? I'd rather we do it less optimally with the tooling in place (then eventually do it super proper) than to put immediate resources learning the intricacies of Redis best practice for example. That's why I'd trade a bit of "best practice" for less implementation overhead

Obviously, this might be impossible and that cool too. I guess we'll be clear on that pretty soon

**Comment by aconanlai** [comment]
ok, gotcha - i think we can use mongodb for everything

**Comment by aconanlai** [comment]
https://github.com/n10as/n20.as/commit/8eb71d974d930f811e5108343cdc9ede778e8454#commitcomment-19959402

**Comment by aconanlai** [comment]
http://stackoverflow.com/questions/14382725/how-to-get-the-correct-ip-address-of-a-client-into-a-node-socket-io-app-hosted-o

**Comment by aconanlai** [comment]
last few commits were me fiddling with the socket request - finally got it correct, inline comment explains that since heroku proxys the request, we need to check the headers to get correct IP:

https://github.com/n10as/n20.as/commit/7a9aea039c7ef4d637c835e59abd723b071bea92

**Comment by aconanlai** [comment]
https://github.com/n10as/n20.as/commit/4bc923f5001e2f29cae99b3feb03c70bd903bac1

to discuss: proper socket.io error handling - currently, typing '/ban username' crashes system since it expects '/ban [username]

**Comment by aconanlai** [comment]
also, bug, sometimes on a non-index route on client, socket doesn't register initial userlist and chatlist populating events... will look into

**Comment by kuzyn** [comment]
@aconanlai I think that you did edit2 in 5b73c68 right?

as for crash in [here](https://github.com/n10as/n20.as/commit/5b73c68c4b9e75fa73ae78626d5123821975cde2#diff-2f27eecc6d25a27b8e0ad87635596078L164), can you walk me through? I don't clearly see where the error could come from. Was is because the regex was not completely escaped?

**Comment by aconanlai** [comment]
yup, https://github.com/n10as/n20.as/commit/5b73c68c4b9e75fa73ae78626d5123821975cde2 fixes it

this is the error i'm talking about: `/Users/intern/Desktop/n20.as/init.js:46
  throw error;
  ^

TypeError: Cannot read property 'pop' of null
`

it occurs when the message doesn't include a '[' and a ']', so the array is null and the pop() failed - just need a try-catch i guess

**Comment by kuzyn** [comment]
That's not a node error tho; it's a js error ;) 

You can test that your regex !== null before the pop(), or you can access your array[0] and deal with the null after. Pop is not really useful in this case, since we're discarding our array afterward anyway

But I think that even better will be to just have a more flexible regex that will match both

**Comment by aconanlai** [comment]
yup, just a JS error, not node - i was just pointing it out as a TODO reminder for myself

i picked brackets arbitrarily so we have some way to encapsulate the username so we can split up the username and the 'reason' - so like

`/ban [icky] bad chatter`

otherwise

`/ban icky bad chatter` 

how do we know where username ends and 'reason begins?

-----

nickname what do you have in mind? we allowed everything on n10.as 1.0

**Comment by kuzyn** [comment]
I see I see. I got that but wondered more about the bracket themselves, since it means having to escape them when we regex. Other characters would be less annoying to deal with imo:
```
/ban mrbigcheeze "go home"
```

As for filters: let's talk about it later. I think that most things should be okay, but we def. do not want to have to spent time dealing with return lines and non-ascii and what not

**Comment by kuzyn** [comment]
lol nvm we need to escape them as well in js i guess 🚜

**Comment by kuzyn** [comment]
let's keep this here for ref & discussion but close the issue
